{
  "formatVersion": "1.1",
  "component": {
    "group": "cc.nitea",
    "module": "nitea-neoforge-1.20.1",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nitea-neoforge-1.20.1-0.4.0-sources.jar",
          "url": "nitea-neoforge-1.20.1-0.4.0-sources.jar",
          "size": 49762,
          "sha512": "a1abc0d30a1eac9300df5696f46984d2256e3ab44b8518de3915c0cb2fa1f7e2f04c6e388f9d10733b6922beb2d4b3b9085b917aff9242c2c50fb50a2fb4c228",
          "sha256": "032b541fe2f3885d519352f424d7847867985a787388e857fcf3a6627b968eda",
          "sha1": "0900c0f10aa2ff3fd567c8f9a18d097900a21294",
          "md5": "bf12771d1eb4b56f0af64b8c6bd46081"
        }
      ]
    },
    {
      "name": "reobfRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nitea-neoforge-1.20.1-0.4.0.jar",
          "url": "nitea-neoforge-1.20.1-0.4.0.jar",
          "size": 82989,
          "sha512": "1d84f9dbe76bf244aa004c1ff7a25754d4f0b9261548dcae1c0a748b923c5254fc1d215429b0f1b03bd3994324c207c3c7f192f34eeb1063759f07a368c1723c",
          "sha256": "d82448c74f1ea7e26c7689102b1d7f8edaef94ee44001914d7224e293a195615",
          "sha1": "eca10b02a858e4ce97023b636793a963b6282424",
          "md5": "ecaaca192780f12a930c79508be7687d"
        }
      ]
    },
    {
      "name": "reobfApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "nitea-neoforge-1.20.1-0.4.0.jar",
          "url": "nitea-neoforge-1.20.1-0.4.0.jar",
          "size": 82989,
          "sha512": "1d84f9dbe76bf244aa004c1ff7a25754d4f0b9261548dcae1c0a748b923c5254fc1d215429b0f1b03bd3994324c207c3c7f192f34eeb1063759f07a368c1723c",
          "sha256": "d82448c74f1ea7e26c7689102b1d7f8edaef94ee44001914d7224e293a195615",
          "sha1": "eca10b02a858e4ce97023b636793a963b6282424",
          "md5": "ecaaca192780f12a930c79508be7687d"
        }
      ]
    }
  ]
}
